<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>C_Compiler</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>$(SolutionDir)bin</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="TestPrograms\*.py" />
    <Content Include="TestPrograms\*.c" />
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="System.Collections.Immutable" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="stdfish.c">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="test.c">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
