using CodeGeneration;
using CTilde.Expr;
using CTilde.FishAsm;
using Fishmachine.CTilde.FishAsm;
using Fishmachine.VM;
using System;
using System.CodeDom;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace CTilde.Langs
{
	public partial class FishAsmProvider : LangProvider
	{
		//bool OmmitSemicolon = false;
		FishCompileState State;

		public FishAsmProvider(FishCompileState State)
		{
			this.State = State;

			EmitRaw("# Generated by C~");
			EmitRaw("# Labels generate in the bytecode bin as the show up in the code, adjecent labels share address by design");
			EmitRaw("# int_table address is set by the VM when the program runs");
			EmitRaw("# All global variables except functions are supposed to be stored using double indirection");
			EmitRaw("# Assignment to global variables which are arrays, strings or pointer types should change the address of the variable");
			EmitRaw("# Assignment to non-pointer global variables should assign their value, not their address.");
			EmitRaw("# Dereference of non-pointer globals should return their value");
			EmitRaw("# Dereference of pointer and string globals should return their reference");

		}

		string FormatArgs(object[] args)
		{
			string[] argsStr = new string[args.Length];

			for (int i = 0; i < args.Length; i++)
			{
				if (args[i] is Reg R)
				{
					argsStr[i] = FishUtils.RegToString(R);
				}
				else if (args[i] is uint UI)
				{
					argsStr[i] = string.Format("${0}", UI);
				}
				else
				{
					argsStr[i] = args[i].ToString();
				}
			}

			return string.Join(", ", argsStr);
		}

		const bool SkipDuplicates = true;
		FishInst LastInst;
		object[] LastArgs;
		FishInst[] AllowSkip = new FishInst[] { FishInst.MOVE_REG_OFFSET_REG };

		void EmitInstruction(FishInst inst, params object[] args)
		{
			if (SkipDuplicates)
			{
				if (inst == LastInst && args.Length == LastArgs.Length && args.SequenceEqual(LastArgs) && AllowSkip.Contains(inst))
				{
					//EmitRawUnindented("# Skipping duplicate instruction {0} {1}", inst, FormatArgs(args));
					return;
				}

				LastInst = inst;
				LastArgs = args;
			}

			AppendLine("{0} {1}", inst, FormatArgs(args));
		}

		void EmitRaw(string raw)
		{
			AppendLine(raw);
		}

		void EmitRaw(string fmt, params object[] args)
		{
			EmitRaw(string.Format(fmt, args));
		}

		void EmitRawUnindented(string fmt, params object[] args)
		{
			bool Unindented = false;
			if (Unindent())
				Unindented = true;

			EmitRaw(string.Format(fmt, args));

			if (Unindented)
				Indent();
		}

		void EmitLabels()
		{
			FishLabel[] Lbls = State.GetNewLabels();

			foreach (FishLabel L in Lbls)
			{
				EmitRaw(L.Name + ":");
				Indent();

				if (L.Value.StartsWith("\"") && L.Value.EndsWith("\""))
				{
					EmitRaw(".String {0}", L.Value);
				}
				else if (L.Value.Contains(".") || L.Value.EndsWith("f"))
				{
					EmitRaw(".float {0}", L.Value);
				}
				else
				{
					EmitRaw(".long {0}", L.Value);
				}

				Unindent();
			}
		}

		void EmitReturn()
		{
			EmitInstruction(FishInst.LEAVE);
			EmitInstruction(FishInst.RET);
		}

		void EmitLoadFromAddress(int size, int offset, Reg SrcAddr, Reg DstReg, bool isunsigned)
		{
			if (size == 0)
			{
				EmitInstruction(FishInst.LEA_OFFSET_REG_REG, offset, SrcAddr, DstReg);
			}
			else if (size == 4)
			{
				EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, offset, SrcAddr, DstReg);

			}
			else if (size == 2)
			{
				if (DstReg == Reg.EAX)
				{
					EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, offset, SrcAddr, Reg.AL);
					EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, offset + 1, SrcAddr, Reg.AH);
				}
				else if (DstReg == Reg.EBX)
				{
					EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, offset, SrcAddr, Reg.BL);
					EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, offset + 1, SrcAddr, Reg.BH);
				}
				else
					throw new NotImplementedException();
			}
			else if (size == 1)
			{
				if (isunsigned)
					EmitInstruction(FishInst.MOVEBYTE_OFFSET_REG_REG, offset, SrcAddr, DstReg);
				else
					EmitInstruction(FishInst.MOVES_OFFSET_REG_REG, offset, SrcAddr, DstReg);
			}
			else
				throw new NotImplementedException();
		}

		void EmitStoreToAddress(int size, int offset, Reg SrcReg, Reg DstAddr, bool isunsigned, bool useEBX)
		{
			if (useEBX)
				DstAddr = Reg.EBX;

			if (size == 4)
			{
				EmitInstruction(FishInst.MOVE_REG_OFFSET_REG, SrcReg, offset, DstAddr);
			}
			else if (size == 2)
			{
				if (SrcReg == Reg.EAX)
				{
					EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.AL, offset, DstAddr);
					EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.AH, offset + 1, DstAddr);
				}
				else if (SrcReg == Reg.EBX)
				{
					EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.BL, offset, DstAddr);
					EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, Reg.BH, offset + 1, DstAddr);
				}
				else
					throw new NotImplementedException();
			}
			else if (size == 1)
			{
				EmitInstruction(FishInst.MOVEBYTE_REG_OFFSET_REG, SrcReg, offset, DstAddr);
			}
			else
				throw new NotImplementedException();
		}

		void FetchIdentifier(string name, int size, bool ispointer, Reg DestReg, bool isunsigned, bool sumEBX/*, bool fetchaddress*/)
		{
			var vType = State.GetVarType(name);
			bool isGlobal = State.IsVarGlobal(name);
			bool isArrayLike = vType.IsArray || (isGlobal && Expr_TypeDef.IsPointerType(vType));

			if (isGlobal)
			{
				Reg baseReg = Reg.EDX;
				EmitInstruction(FishInst.MOVE_LONG_REG, name, baseReg);

				// First dereference: get the intermediate pointer address
				EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, baseReg, baseReg);

				// For POINTER-type globals (not arrays!), do a second dereference when accessing values
				// Arrays store their data directly at the intermediate address
				if (Expr_TypeDef.IsPointerType(vType) && !vType.IsArray && (sumEBX || size != 0))
				{
					EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, baseReg, baseReg);
				}

				if (sumEBX)
					EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, baseReg);

				// Load value when a value is requested; return address only when size == 0
				if (size != 0)
				{
					EmitLoadFromAddress(size, 0, baseReg, DestReg, isunsigned);
				}
				else
				{
					if (DestReg != baseReg)
						EmitInstruction(FishInst.MOVE_REG_REG, baseReg, DestReg);
				}

				return;
			}

			int VarOffset = State.GetVarOffset(name);

			if (ispointer && !isArrayLike)
			{
				// Local/param pointer: load the pointer value
				EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, VarOffset, Reg.EBP, Reg.EDX);

				if (sumEBX)
				{
					EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, Reg.EDX);

					if (size != 0)
						EmitLoadFromAddress(size, 0, Reg.EDX, DestReg, isunsigned);
					else if (DestReg != Reg.EDX)
						EmitInstruction(FishInst.MOVE_REG_REG, Reg.EDX, DestReg);
					else
						throw new NotImplementedException();
				}
				else
				{
					if (DestReg != Reg.EDX)
						EmitInstruction(FishInst.MOVE_REG_REG, Reg.EDX, DestReg);
					else
						throw new NotImplementedException();
				}
			}
			else
			{
				// Non-pointer local (scalar or stack array) or array-like
				if (size == 0 || isArrayLike)
				{
					EmitInstruction(FishInst.LEA_OFFSET_REG_REG, VarOffset, Reg.EBP, DestReg);
					if (sumEBX)
						EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, DestReg);
				}
				else
				{
					if (sumEBX)
					{
						EmitInstruction(FishInst.LEA_OFFSET_REG_REG, VarOffset, Reg.EBP, Reg.EDX);
						EmitInstruction(FishInst.ADD_REG_REG, Reg.EBX, Reg.EDX);
						EmitLoadFromAddress(size, 0, Reg.EDX, DestReg, isunsigned);
					}
					else
					{
						EmitLoadFromAddress(size, VarOffset, Reg.EBP, DestReg, isunsigned);
					}
				}
			}
		}

		void StoreIdentifier(string name, int size, bool ispointer, Reg SrcReg, bool isunsigned, bool storeaddress)
		{
			if (State.IsVarGlobal(name))
			{
				EmitInstruction(FishInst.MOVE_LONG_REG, name, Reg.EBX);

				if (!storeaddress)
					EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, Reg.EBX, Reg.EBX);

				EmitStoreToAddress(size, 0, SrcReg, Reg.EBX, isunsigned, false);
			}
			else
			{
				int VarOffset = State.GetVarOffset(name);
				EmitStoreToAddress(size, VarOffset, SrcReg, Reg.EBP, isunsigned, false);
			}
		}

		void StoreIdentifier(string name, int size, bool ispointer, Reg SrcReg, Reg DstAddr, bool isunsigned, bool useEBX)
		{
			if (State.IsVarGlobal(name))
			{
				// For globals, DstAddr (or EBX) already contains the computed address
				// Just write directly to it
				EmitStoreToAddress(size, 0, SrcReg, DstAddr, isunsigned, useEBX);
			}
			else
			{
				int VarOffset = State.GetVarOffset(name);

				if (useEBX)
					EmitStoreToAddress(size, 0, SrcReg, Reg.EBX, isunsigned, true);
				else
					EmitStoreToAddress(size, VarOffset, SrcReg, Reg.EBP, isunsigned, false);
			}
		}

		void EmitBranch(ComparisonOp Op, bool Inverted, string JumpLabel)
		{
			switch (Op)
			{
				case ComparisonOp.Equals:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_NOT_ZERO_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_ZERO_LONG, JumpLabel);
					}
					break;

				case ComparisonOp.NotEquals:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_ZERO_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_NOT_ZERO_LONG, JumpLabel);
					}
					break;

				case ComparisonOp.LessThan:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_GREATEQ_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_LESS_LONG, JumpLabel);

					}
					break;

				case ComparisonOp.LessThanOrEqual:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_GREAT_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_LESSEQ_LONG, JumpLabel);
					}
					break;

				case ComparisonOp.GreaterThan:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_LESSEQ_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_GREAT_LONG, JumpLabel);
					}
					break;

				case ComparisonOp.GreaterThanOrEqual:
					if (Inverted)
					{
						EmitInstruction(FishInst.JUMP_IF_LESS_LONG, JumpLabel);
					}
					else
					{
						EmitInstruction(FishInst.JUMP_IF_GREATEQ_LONG, JumpLabel);
					}
					break;

				default:
					throw new NotImplementedException();
			}
		}

		Expr_TypeDef GetExpressionType(Expression E)
		{
			if (E is Expr_Identifier IdEx)
			{
				Expr_TypeDef TD = State.GetVarType(IdEx.Identifier);
				return TD;
			}
			else if (E is Expr_ConstNumber NumEx)
			{
				Expr_TypeDef TD = new Expr_TypeDef();
				TD.Type = "uint";
				return TD;
			}
			else if (E is Expr_IndexOp IndEx)
			{
				Expr_TypeDef td = State.GetVarType((IndEx.LExpr as Expr_Identifier).Identifier);
				if (State.Types.TryGetType(td.Type, out FishTypeDef FT))
					if (FT is FishStructDef FST)
						return FST.GetFieldType(((Expr_MemberAccessOp)IndEx.IndexValExpr).MemberName);
			}

			throw new NotImplementedException();
		}

		void EmitTestBranch(Expression Cond, bool Inverted, string JumpLabel)
		{
			EmitRaw("# BEGIN EmitTestBranch for condition: {0}, Inverted {1}, JumpLabel '{2}'", Cond.ToSourceStr(), Inverted ? 1u : 0u, JumpLabel);
			Indent();

			if (Cond is Expr_ComparisonOp Cmp)
			{
				Compile(Cond); // sets flags for EAX vs ECX
				EmitBranch(Cmp.Op, true, JumpLabel);
			}
			else if (Cond is Expr_ConstNumber CNum)
			{
				if (CNum.NumberLiteral == "1")
				{
					EmitInstruction(FishInst.NOP);
				}
				else if (CNum.NumberLiteral == "0")
				{
					EmitInstruction(FishInst.JUMP_LONG, JumpLabel);
				}
				else
					throw new NotImplementedException();
			}
			else if (Cond is Expr_BinaryOp BinOp)
			{
				//Compile(BinOp.LExpr);
				//Compile(BinOp.RExpr);
				EmitInstruction(FishInst.TEST_REG_REG, Reg.EAX, Reg.EAX);
				EmitInstruction(FishInst.JUMP_IF_ZERO_LONG, JumpLabel);

				//throw new NotImplementedException();
			}
			else if (Cond is Expr_FuncCall FuncCallExpr)
			{
				Compile(Cond);
				EmitInstruction(FishInst.DBG_REGS);
				EmitInstruction(FishInst.TEST_REG_REG, Reg.EAX, Reg.EAX);
				EmitBranch(ComparisonOp.Equals, false, JumpLabel);
				//throw new NotImplementedException();
			}
			else if (Cond is Expr_Identifier IdExpr)
			{
				Compile(IdExpr);
			}
			else
				throw new NotImplementedException();

			Unindent();
			EmitRaw("# END EmitTestBranch for condition: {0}, Inverted {1}, JumpLabel '{2}'", Cond.ToSourceStr(), Inverted ? 1u : 0u, JumpLabel);
		}

		void EmitStoreToIdent(string SourceStr, Expression ValueExpr, Expr_Identifier Ident)
		{
			EmitRaw("# AssignValue Identifier");

			Compile(ValueExpr);

			Expr_TypeDef td = State.GetVarType(Ident.Identifier);
			int sz = Expr_TypeDef.GetRawTypeSize(State.Types, td);

			EmitRaw("# Expr_AssignVariable '{0}' BEGIN", SourceStr);
			EmitRaw("# Assign to '{0}'", Ident.Identifier);
			Indent();

			/*if (AssVariable.Variable.Identifier == "temp_buffer")
				Debugger.Break();*/
			/***bool storeaddress = true;

			if (State.IsVarGlobal(AssVariable.Variable.Identifier))
			{
				//bool PtrType = Expr_TypeDef.IsPointerType(td);

				storeaddress = false;
			}*/

			bool storeaddress = !State.IsVarGlobal(Ident.Identifier);
			//bool storeaddress = true;

			StoreIdentifier(Ident.Identifier, sz, td.IsPointer, Reg.EAX, Expr_TypeDef.IsUnsigned(td.Type), storeaddress);

			Unindent();
			EmitRaw("# Expr_AssignVariable '{0}' END", SourceStr);
		}


		// Emits a single function call argument onto the stack in right-to-left order context.
		// - Identifiers of array-like storage (globals declared as static string[N] or actual arrays) decay to address.
		// - Pointer variables (locals/params) push their pointer value.
		// - Indexing into array-like lvalues passes the element address when appropriate.
		// - All others evaluate to value in EAX and are pushed.
		void EmitCallArg(Expression arg)
		{
			// Identifier fast-path
			if (arg is Expr_Identifier id)
			{
				var t = State.GetVarType(id.Identifier);
				bool isGlobal = State.IsVarGlobal(id.Identifier);
				bool isArrayLike = t.IsArray || (isGlobal && Expr_TypeDef.IsPointerType(t) && !t.IsPointer);

				if (isArrayLike)
				{
					// Array-to-pointer decay: push address
					FetchIdentifier(id.Identifier, 0, /*ispointer*/ false, Reg.EAX, /*isunsigned*/ true, /*sumEBX*/ false);
					EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
					return;
				}

				if (t.IsPointer)
				{
					if (isGlobal)
					{
						// Global pointer: need double dereference to get the actual pointer value
						EmitInstruction(FishInst.MOVE_LONG_REG, id.Identifier, Reg.EDX);
						EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, Reg.EDX, Reg.EDX);  // Get intermediate pointer storage
						EmitInstruction(FishInst.MOVE_OFFSET_REG_REG, 0, Reg.EDX, Reg.EAX);  // Get actual heap address
						EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
					}
					else
					{
						// Local pointer: just fetch the pointer value (single deref from stack)
						FetchIdentifier(id.Identifier, 4, /*ispointer*/ true, Reg.EAX, /*isunsigned*/ true, /*sumEBX*/ false);
						EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
					}
					return;
				}

				// Scalar: evaluate and push value
				Compile(arg);

				//if (Expr_TypeDef.IsFloatType(t))
				//{
				//Debugger.Break();
				//	EmitInstruction(FishInst.PUSH_REG, Reg.ST0);
				//}
				//else
				//{
				EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
				//}
				return;
			}

			// Indexing: if indexing into array-like, pass the element address; otherwise value
			if (arg is Expr_IndexOp idx && idx.LExpr is Expr_Identifier baseId)
			{
				var t = State.GetVarType(baseId.Identifier);
				bool isGlobal = State.IsVarGlobal(baseId.Identifier);
				bool isArrayLike = t.IsArray || (isGlobal && Expr_TypeDef.IsPointerType(t));

				if (isArrayLike)
				{
					// Compute address only
					bool prev = State.IndexEmitOnlyAddress;
					State.IndexEmitOnlyAddress = true;
					Compile(arg);                // EAX = &base[index]
					State.IndexEmitOnlyAddress = prev;

					EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
					return;
				}
			}

			// Literals and all other expressions: evaluate and push value
			Compile(arg);                      // EAX holds value or address for const string
			EmitInstruction(FishInst.PUSH_REG, Reg.EAX);
		}
	}
}