# Generated by C~
# Labels generate in the bytecode bin as the show up in the code, adjecent labels share address by design
# int_table address is set by the VM when the program runs
# VariableDef BEGIN - int_table
    .globl int_table
# VariableDef END - int_table
# VariableDef BEGIN - temp_buffer
    .globl temp_buffer
    temp_buffer:
# VariableDef END - temp_buffer
# VariableAssign BEGIN
    .STATVAR_0002:
    .Raw 50, 0
# VariableAssign END
# VariableDef BEGIN - temp_buffer2
    .globl temp_buffer2
    temp_buffer2:
# VariableDef END - temp_buffer2
# VariableAssign BEGIN
    .STATVAR_0005:
    .Raw 50, 0
# VariableAssign END
# VariableDef BEGIN - input_length
    .globl input_length
    input_length:
# VariableDef END - input_length
# VariableAssign BEGIN
    .long 50
# VariableAssign END
# VariableDef BEGIN - input_count
    .globl input_count
    input_count:
# VariableDef END - input_count
# VariableAssign BEGIN
    .long 0
# VariableAssign END
.globl print
print:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # VariableDef BEGIN - i
        SUB_LONG_REG $4, %esp
    # VariableDef END - i
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -4, %ebp
    # VariableAssign END
    # While BEGIN
        .WHILE_000A:
        # Expr_ComparisonOp BEGIN
            MOVE_LONG_REG $0, %eax
            PUSH_REG %eax
            MOVE_REG_REG %eax, %ebx
            # IndexOp BEGIN
                #: EAX = i
                LEA_OFFSET_REG_REG -4, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                MOVE_REG_REG %eax, %ebx
                #: str[EBX]
                LEA_OFFSET_REG_REG 8, %ebp, %eax
                ADD_REG_REG %ebx, %eax
                MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            # IndexOp END
            MOVE_REG_REG %eax, %ebx
            POP_REG %eax
            #: str[i] != 0
            #: EAX - EBX semantics
            CMP_REG_REG %eax, %ebx
        # Expr_ComparisonOp END
        JUMP_IF_ZERO_LONG .ENDWHILE_000C
        PUSH_REG %ebx
        PUSH_REG %eax
        # syscall_2 BEGIN
            # IndexOp BEGIN
                #: EAX = i
                LEA_OFFSET_REG_REG -4, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                MOVE_REG_REG %eax, %ebx
                #: str[EBX]
                LEA_OFFSET_REG_REG 8, %ebp, %eax
                ADD_REG_REG %ebx, %eax
                MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            # IndexOp END
            PUSH_REG %eax
            MOVE_LONG_REG $1, %eax
            PUSH_REG %eax
            SYSCALL_2 
        # syscall_2 END
        # Expr_IncDecOp BEGIN
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            ADD_LONG_REG $1, %eax
            MOVE_REG_OFFSET_REG %eax, -4, %ebp
        # Expr_IncDecOp END
        POP_REG %eax
        POP_REG %ebx
        JUMP_LONG .WHILE_000A
        .ENDWHILE_000C:
    # While END
    LEAVE 
    RET 
.globl printnum
printnum:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # syscall_2 BEGIN
        LEA_OFFSET_REG_REG 8, %ebp, %eax
        MOVE_OFFSET_REG_REG 0, %eax, %eax
        PUSH_REG %eax
        MOVE_LONG_REG $2, %eax
        PUSH_REG %eax
        SYSCALL_2 
    # syscall_2 END
    LEAVE 
    RET 
# VariableDef BEGIN - tmp_chr
    .globl tmp_chr
    tmp_chr:
# VariableDef END - tmp_chr
# VariableAssign BEGIN
    .STATVAR_0010:
    .Raw 2, 0
# VariableAssign END
.globl printchar
printchar:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # Expr_AssignValue BEGIN
        # IndexOp BEGIN
            #: EAX = 0
            MOVE_LONG_REG $0, %eax
            MOVE_REG_REG %eax, %ebx
            #: tmp_chr[EBX]
            ADD_LONG_REG tmp_chr, %eax
        # IndexOp END
        MOVE_REG_REG %eax, %ebx
        LEA_OFFSET_REG_REG 8, %ebp, %eax
        MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
        MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
    # Expr_AssignValue END
    # Expr_AssignValue BEGIN
        # IndexOp BEGIN
            #: EAX = 1
            MOVE_LONG_REG $1, %eax
            MOVE_REG_REG %eax, %ebx
            #: tmp_chr[EBX]
            ADD_LONG_REG tmp_chr, %eax
        # IndexOp END
        MOVE_REG_REG %eax, %ebx
        MOVE_LONG_REG $0, %eax
        MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
    # Expr_AssignValue END
    # FuncCall BEGIN - print
        MOVE_LONG_REG tmp_chr, %ebx
        MOVEBYTE_OFFSET_REG_REG 0, %ebx, %eax
        PUSH_REG %eax
        MOVE_LONG_REG print, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - print
    LEAVE 
    RET 
.globl memory_copy
memory_copy:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # VariableDef BEGIN - i
        SUB_LONG_REG $4, %esp
    # VariableDef END - i
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -4, %ebp
    # VariableAssign END
    # VariableDef BEGIN - tmp
        SUB_LONG_REG $1, %esp
    # VariableDef END - tmp
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -8, %ebp
    # VariableAssign END
    # While BEGIN
        .WHILE_0014:
        # Expr_ComparisonOp BEGIN
            LEA_OFFSET_REG_REG 16, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            PUSH_REG %eax
            MOVE_REG_REG %eax, %ebx
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            MOVE_REG_REG %eax, %ebx
            POP_REG %eax
            #: i < len
            #: EAX - EBX semantics
            CMP_REG_REG %eax, %ebx
        # Expr_ComparisonOp END
        JUMP_IF_GREATEQ_LONG .ENDWHILE_0016
        PUSH_REG %ebx
        PUSH_REG %eax
        # IndexOp BEGIN
            #: EAX = i
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            MOVE_REG_REG %eax, %ebx
            #: source[EBX]
            LEA_OFFSET_REG_REG 12, %ebp, %eax
            ADD_REG_REG %ebx, %eax
        # IndexOp END
        # Expr_AssignValue BEGIN
            MOVEBYTE_REG_OFFSET_REG %eax, -8, %ebp
        # Expr_AssignValue END
        # Expr_AssignValue BEGIN
            # IndexOp BEGIN
                #: EAX = i
                LEA_OFFSET_REG_REG -4, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                MOVE_REG_REG %eax, %ebx
                #: dest[EBX]
                LEA_OFFSET_REG_REG 8, %ebp, %eax
                ADD_REG_REG %ebx, %eax
            # IndexOp END
            MOVE_REG_REG %eax, %ebx
            LEA_OFFSET_REG_REG -8, %ebp, %eax
            MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
        # Expr_AssignValue END
        # Expr_IncDecOp BEGIN
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            ADD_LONG_REG $1, %eax
            MOVE_REG_OFFSET_REG %eax, -4, %ebp
        # Expr_IncDecOp END
        POP_REG %eax
        POP_REG %ebx
        JUMP_LONG .WHILE_0014
        .ENDWHILE_0016:
    # While END
    LEAVE 
    RET 
.globl memory_clear
memory_clear:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # VariableDef BEGIN - i
        SUB_LONG_REG $4, %esp
    # VariableDef END - i
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -4, %ebp
    # VariableAssign END
    # FuncCall BEGIN - print
        MOVE_LONG_REG .L_0019, %eax
        PUSH_REG %eax
        MOVE_LONG_REG print, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - print
    # FuncCall BEGIN - printnum
        LEA_OFFSET_REG_REG 8, %ebp, %eax
        MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
        PUSH_REG %eax
        MOVE_LONG_REG printnum, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - printnum
    # FuncCall BEGIN - print
        MOVE_LONG_REG .L_001A, %eax
        PUSH_REG %eax
        MOVE_LONG_REG print, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - print
    # FuncCall BEGIN - printnum
        LEA_OFFSET_REG_REG 12, %ebp, %eax
        MOVE_OFFSET_REG_REG 0, %eax, %eax
        PUSH_REG %eax
        MOVE_LONG_REG printnum, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - printnum
    # FuncCall BEGIN - print
        MOVE_LONG_REG .L_001B, %eax
        PUSH_REG %eax
        MOVE_LONG_REG print, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - print
    # While BEGIN
        .WHILE_001C:
        # Expr_ComparisonOp BEGIN
            LEA_OFFSET_REG_REG 12, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            PUSH_REG %eax
            MOVE_REG_REG %eax, %ebx
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            MOVE_REG_REG %eax, %ebx
            POP_REG %eax
            #: i < len
            #: EAX - EBX semantics
            CMP_REG_REG %eax, %ebx
        # Expr_ComparisonOp END
        JUMP_IF_GREATEQ_LONG .ENDWHILE_001E
        PUSH_REG %ebx
        PUSH_REG %eax
        # Expr_AssignValue BEGIN
            # IndexOp BEGIN
                #: EAX = i
                LEA_OFFSET_REG_REG -4, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                MOVE_REG_REG %eax, %ebx
                #: dest[EBX]
                LEA_OFFSET_REG_REG 8, %ebp, %eax
                ADD_REG_REG %ebx, %eax
            # IndexOp END
            MOVE_REG_REG %eax, %ebx
            MOVE_LONG_REG $0, %eax
            MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
        # Expr_AssignValue END
        # Expr_IncDecOp BEGIN
            LEA_OFFSET_REG_REG -4, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            ADD_LONG_REG $1, %eax
            MOVE_REG_OFFSET_REG %eax, -4, %ebp
        # Expr_IncDecOp END
        POP_REG %eax
        POP_REG %ebx
        JUMP_LONG .WHILE_001C
        .ENDWHILE_001E:
    # While END
    LEAVE 
    RET 
.globl input_add
input_add:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # If BEGIN
        #: c == '\b'
        # Expr_ComparisonOp BEGIN
            MOVES_LONG_REG $8, %eax
            PUSH_REG %eax
            MOVE_REG_REG %eax, %ebx
            LEA_OFFSET_REG_REG 8, %ebp, %eax
            MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            MOVE_REG_REG %eax, %ebx
            POP_REG %eax
            #: c == '\b'
            #: EAX - EBX semantics
            CMP_REG_REG %eax, %ebx
        # Expr_ComparisonOp END
        JUMP_IF_ZERO_LONG .ENDIF_0021
        # If BEGIN
            #: input_count > 0
            # Expr_ComparisonOp BEGIN
                MOVE_LONG_REG $0, %eax
                PUSH_REG %eax
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG input_count, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                MOVE_REG_REG %eax, %ebx
                POP_REG %eax
                #: input_count > 0
                #: EAX - EBX semantics
                CMP_REG_REG %eax, %ebx
            # Expr_ComparisonOp END
            JUMP_IF_GREAT_LONG .ENDIF_0023
            # Expr_IncDecOp BEGIN
                MOVE_LONG_REG input_count, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                SUB_LONG_REG $1, %eax
                MOVE_LONG_REG input_count, %ebx
                MOVE_REG_OFFSET_REG %eax, 0, %ebx
            # Expr_IncDecOp END
            # Expr_AssignValue BEGIN
                # IndexOp BEGIN
                    #: EAX = input_count
                    MOVE_LONG_REG input_count, %ebx
                    MOVE_OFFSET_REG_REG 0, %ebx, %eax
                    MOVE_REG_REG %eax, %ebx
                    #: temp_buffer[EBX]
                    ADD_LONG_REG temp_buffer, %eax
                # IndexOp END
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG $0, %eax
                MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
            # Expr_AssignValue END
            # Expr_ReturnStatement BEGIN
                LEAVE 
                RET 
            # Expr_ReturnStatement END
            .ENDIF_0023:
        # If END
        .ENDIF_0021:
    # If END
    # If BEGIN
        #: input_count < (input_length - 1)
        # Expr_ComparisonOp BEGIN
            # MathOp BEGIN (-)
                PUSH_REG %ebx
                MOVE_LONG_REG $1, %eax
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG input_length, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                SUB_REG_REG %ebx, %eax
                POP_REG %ebx
            # MathOp END (-)
            PUSH_REG %eax
            MOVE_REG_REG %eax, %ebx
            MOVE_LONG_REG input_count, %ebx
            MOVE_OFFSET_REG_REG 0, %ebx, %eax
            MOVE_REG_REG %eax, %ebx
            POP_REG %eax
            #: input_count < (input_length - 1)
            #: EAX - EBX semantics
            CMP_REG_REG %eax, %ebx
        # Expr_ComparisonOp END
        JUMP_IF_LESS_LONG .ENDIF_0025
        # Expr_AssignValue BEGIN
            # IndexOp BEGIN
                #: EAX = input_count
                MOVE_LONG_REG input_count, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                MOVE_REG_REG %eax, %ebx
                #: temp_buffer[EBX]
                ADD_LONG_REG temp_buffer, %eax
            # IndexOp END
            MOVE_REG_REG %eax, %ebx
            LEA_OFFSET_REG_REG 8, %ebp, %eax
            MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
        # Expr_AssignValue END
        # Expr_IncDecOp BEGIN
            MOVE_LONG_REG input_count, %ebx
            MOVE_OFFSET_REG_REG 0, %ebx, %eax
            ADD_LONG_REG $1, %eax
            MOVE_LONG_REG input_count, %ebx
            MOVE_REG_OFFSET_REG %eax, 0, %ebx
        # Expr_IncDecOp END
        # FuncCall BEGIN - printchar
            LEA_OFFSET_REG_REG 8, %ebp, %eax
            MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            PUSH_REG %eax
            MOVE_LONG_REG printchar, %eax
            CALL_REG %eax
            ADD_LONG_REG $4, %esp
        # FuncCall END - printchar
        .ENDIF_0025:
    # If END
    LEAVE 
    RET 
.globl input_readline
input_readline:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # VariableDef BEGIN - ret
        SUB_LONG_REG $4, %esp
    # VariableDef END - ret
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -4, %ebp
    # VariableAssign END
    # VariableDef BEGIN - idx
        SUB_LONG_REG $4, %esp
    # VariableDef END - idx
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -8, %ebp
    # VariableAssign END
    # VariableDef BEGIN - chr
        SUB_LONG_REG $1, %esp
    # VariableDef END - chr
    # VariableAssign BEGIN
        MOVE_LONG_REG $0, %eax
        MOVE_REG_OFFSET_REG %eax, -12, %ebp
    # VariableAssign END
    # Expr_AssignValue BEGIN
        # IndexOp BEGIN
            #: EAX = 0
            MOVE_LONG_REG $0, %eax
            MOVE_REG_REG %eax, %ebx
            #: dst[EBX]
            LEA_OFFSET_REG_REG 8, %ebp, %eax
            ADD_REG_REG %ebx, %eax
        # IndexOp END
        MOVE_REG_REG %eax, %ebx
        MOVE_LONG_REG $0, %eax
        MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
    # Expr_AssignValue END
    # While BEGIN
        .WHILE_0028:
        NOP 
        PUSH_REG %ebx
        PUSH_REG %eax
        # If BEGIN
            #: input_count == 0
            # Expr_ComparisonOp BEGIN
                MOVE_LONG_REG $0, %eax
                PUSH_REG %eax
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG input_count, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                MOVE_REG_REG %eax, %ebx
                POP_REG %eax
                #: input_count == 0
                #: EAX - EBX semantics
                CMP_REG_REG %eax, %ebx
            # Expr_ComparisonOp END
            JUMP_IF_ZERO_LONG .ENDIF_002C
            # Continue
            JUMP_LONG .WHILE_0028
            .ENDIF_002C:
        # If END
        # MathOp BEGIN (-)
            PUSH_REG %ebx
            MOVE_LONG_REG $1, %eax
            MOVE_REG_REG %eax, %ebx
            MOVE_LONG_REG input_count, %ebx
            MOVE_OFFSET_REG_REG 0, %ebx, %eax
            SUB_REG_REG %ebx, %eax
            POP_REG %ebx
        # MathOp END (-)
        # Expr_AssignValue BEGIN
            MOVE_REG_OFFSET_REG %eax, -8, %ebp
        # Expr_AssignValue END
        # IndexOp BEGIN
            #: EAX = idx
            LEA_OFFSET_REG_REG -8, %ebp, %eax
            MOVE_OFFSET_REG_REG 0, %eax, %eax
            MOVE_REG_REG %eax, %ebx
            #: temp_buffer[EBX]
            ADD_LONG_REG temp_buffer, %eax
        # IndexOp END
        # Expr_AssignValue BEGIN
            MOVEBYTE_REG_OFFSET_REG %eax, -12, %ebp
        # Expr_AssignValue END
        # FuncCall BEGIN - printchar
            MOVES_LONG_REG $10, %eax
            PUSH_REG %eax
            MOVE_LONG_REG printchar, %eax
            CALL_REG %eax
            ADD_LONG_REG $4, %esp
        # FuncCall END - printchar
        # FuncCall BEGIN - print
            MOVE_LONG_REG .L_002E, %eax
            PUSH_REG %eax
            MOVE_LONG_REG print, %eax
            CALL_REG %eax
            ADD_LONG_REG $4, %esp
        # FuncCall END - print
        # FuncCall BEGIN - printchar
            LEA_OFFSET_REG_REG -12, %ebp, %eax
            MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
            PUSH_REG %eax
            MOVE_LONG_REG printchar, %eax
            CALL_REG %eax
            ADD_LONG_REG $4, %esp
        # FuncCall END - printchar
        # FuncCall BEGIN - printchar
            MOVES_LONG_REG $10, %eax
            PUSH_REG %eax
            MOVE_LONG_REG printchar, %eax
            CALL_REG %eax
            ADD_LONG_REG $4, %esp
        # FuncCall END - printchar
        # If BEGIN
            #: chr == '\n'
            # Expr_ComparisonOp BEGIN
                MOVES_LONG_REG $10, %eax
                PUSH_REG %eax
                MOVE_REG_REG %eax, %ebx
                LEA_OFFSET_REG_REG -12, %ebp, %eax
                MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
                MOVE_REG_REG %eax, %ebx
                POP_REG %eax
                #: chr == '\n'
                #: EAX - EBX semantics
                CMP_REG_REG %eax, %ebx
            # Expr_ComparisonOp END
            JUMP_IF_ZERO_LONG .ENDIF_002F
            # FuncCall BEGIN - memory_copy
                LEA_OFFSET_REG_REG 8, %ebp, %eax
                MOVEBYTE_OFFSET_REG_REG 0, %eax, %eax
                PUSH_REG %eax
                MOVE_LONG_REG temp_buffer, %ebx
                MOVEBYTE_OFFSET_REG_REG 0, %ebx, %eax
                PUSH_REG %eax
                LEA_OFFSET_REG_REG -8, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                PUSH_REG %eax
                MOVE_LONG_REG memory_copy, %eax
                CALL_REG %eax
                ADD_LONG_REG $12, %esp
            # FuncCall END - memory_copy
            # MathOp BEGIN (-)
                PUSH_REG %ebx
                MOVE_LONG_REG $1, %eax
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG input_count, %ebx
                MOVE_OFFSET_REG_REG 0, %ebx, %eax
                SUB_REG_REG %ebx, %eax
                POP_REG %ebx
            # MathOp END (-)
            # Expr_AssignValue BEGIN
                MOVE_REG_OFFSET_REG %eax, -4, %ebp
            # Expr_AssignValue END
            # Expr_AssignValue BEGIN
                # IndexOp BEGIN
                    #: EAX = ret
                    LEA_OFFSET_REG_REG -4, %ebp, %eax
                    MOVE_OFFSET_REG_REG 0, %eax, %eax
                    MOVE_REG_REG %eax, %ebx
                    #: dst[EBX]
                    LEA_OFFSET_REG_REG 8, %ebp, %eax
                    ADD_REG_REG %ebx, %eax
                # IndexOp END
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG $0, %eax
                MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
            # Expr_AssignValue END
            MOVE_LONG_REG $0, %eax
            # Expr_AssignValue BEGIN
                MOVE_LONG_REG input_count, %ebx
                MOVE_REG_OFFSET_REG %eax, 0, %ebx
            # Expr_AssignValue END
            # Expr_AssignValue BEGIN
                # IndexOp BEGIN
                    #: EAX = 0
                    MOVE_LONG_REG $0, %eax
                    MOVE_REG_REG %eax, %ebx
                    #: temp_buffer[EBX]
                    ADD_LONG_REG temp_buffer, %eax
                # IndexOp END
                MOVE_REG_REG %eax, %ebx
                MOVE_LONG_REG $0, %eax
                MOVEBYTE_REG_OFFSET_REG %eax, 0, %ebx
            # Expr_AssignValue END
            DBG_BREAK
            # Expr_ReturnStatement BEGIN
                LEA_OFFSET_REG_REG -4, %ebp, %eax
                MOVE_OFFSET_REG_REG 0, %eax, %eax
                LEAVE 
                RET 
            # Expr_ReturnStatement END
            .ENDIF_002F:
        # If END
        POP_REG %eax
        POP_REG %ebx
        JUMP_LONG .WHILE_0028
        .ENDWHILE_002A:
    # While END
    # Expr_ReturnStatement BEGIN
        LEA_OFFSET_REG_REG -4, %ebp, %eax
        MOVE_OFFSET_REG_REG 0, %eax, %eax
        LEAVE 
        RET 
    # Expr_ReturnStatement END
    LEAVE 
    RET 
.globl handler_int0__impl
handler_int0__impl:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # FuncCall BEGIN - print
        MOVE_LONG_REG .L_0032, %eax
        PUSH_REG %eax
        MOVE_LONG_REG print, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - print
    LEAVE 
    RET 
.globl handler_int0
handler_int0:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    PUSH_REG %eax
    PUSH_REG %ebx
    PUSH_REG %ecx
    PUSH_REG %edx
    PUSH_REG %esi
    PUSH_REG %edi
    MOVE_LONG_REG handler_int0__impl, %eax
    CALL_REG %eax
    POP_REG %edi
    POP_REG %esi
    POP_REG %edx
    POP_REG %ecx
    POP_REG %ebx
    POP_REG %eax
    LEAVE 
    RET 
.globl handler_int1_keyboardkey__impl
handler_int1_keyboardkey__impl:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    LEAVE 
    RET 
.globl handler_int1_keyboardkey
handler_int1_keyboardkey:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    PUSH_REG %eax
    PUSH_REG %ebx
    PUSH_REG %ecx
    PUSH_REG %edx
    PUSH_REG %esi
    PUSH_REG %edi
    MOVE_OFFSET_REG_REG 8, %ebp, %eax
    PUSH_REG %eax
    MOVE_LONG_REG handler_int1_keyboardkey__impl, %eax
    CALL_REG %eax
    ADD_LONG_REG $4, %esp
    POP_REG %edi
    POP_REG %esi
    POP_REG %edx
    POP_REG %ecx
    POP_REG %ebx
    POP_REG %eax
    LEAVE 
    RET 
.globl handler_int2_keyboardchar__impl
handler_int2_keyboardchar__impl:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # FuncCall BEGIN - input_add
        LEA_OFFSET_REG_REG 8, %ebp, %eax
        MOVE_OFFSET_REG_REG 0, %eax, %eax
        PUSH_REG %eax
        MOVE_LONG_REG input_add, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - input_add
    LEAVE 
    RET 
.globl handler_int2_keyboardchar
handler_int2_keyboardchar:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    PUSH_REG %eax
    PUSH_REG %ebx
    PUSH_REG %ecx
    PUSH_REG %edx
    PUSH_REG %esi
    PUSH_REG %edi
    MOVE_OFFSET_REG_REG 8, %ebp, %eax
    PUSH_REG %eax
    MOVE_LONG_REG handler_int2_keyboardchar__impl, %eax
    CALL_REG %eax
    ADD_LONG_REG $4, %esp
    POP_REG %edi
    POP_REG %esi
    POP_REG %edx
    POP_REG %ecx
    POP_REG %ebx
    POP_REG %eax
    LEAVE 
    RET 
.globl kmain
kmain:
    PUSH_REG %ebp
    MOVE_REG_REG %esp, %ebp
    # FuncCall BEGIN - input_add
        MOVES_LONG_REG $72, %eax
        PUSH_REG %eax
        MOVE_LONG_REG input_add, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - input_add
    # FuncCall BEGIN - input_add
        MOVES_LONG_REG $10, %eax
        PUSH_REG %eax
        MOVE_LONG_REG input_add, %eax
        CALL_REG %eax
        ADD_LONG_REG $4, %esp
    # FuncCall END - input_add
    SYSCALL $0
    LEAVE 
    RET 
.L_0019:
    .String "clear "
.L_001A:
    .String "\nlen "
.L_001B:
    .String "\n"
.L_002E:
    .String "- "
.L_0032:
    .String "INT0\n"
