<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath>$(SolutionDir)bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\bin\Debug\net8.0\vm_out.txt" Link="vm_out.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ccompiler\ccompiler.csproj" />
  </ItemGroup>

</Project>
